import { Course } from "@/components/types";

const categories: { id: number, name: string }[] = [
    { id: 1, name: "Mathematics" },
    { id: 2, name: "Physics" },
    { id: 3, name: "Chemistry" },
    { id: 4, name: "Biology" },
    { id: 5, name: "Science" },
    { id: 6, name: "French" },
    { id: 7, name: "English" },
    { id: 8, name: "History" },
    { id: 9, name: "Geography" },
    { id: 10, name: "Philosophy" },
    { id: 11, name: "Economics" },
    { id: 12, name: "Computer Science" },
    { id: 13, name: "Génie Mécanique" },
    { id: 14, name: "Génie Civil" },
    { id: 15, name: "Génie Électrique" },
];

const courses: Course[] = [
        {
            id: 1,
            title: "Calculus 101",
            category: "Mathematics",
            teacher: "Dr. John Doe",
            pictureUrl: "/exmp1.jpg",
            description: "Learn the fundamentals of calculus with real-world examples.",
            students: 150,
            price: 49.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
        {
            id: 2,
            title: "Quantum Mechanics Basics",
            category: "Physics",
            teacher: "Prof. Jane Smith",
            pictureUrl: "/exmp1.jpg",
            description: "Explore the fascinating world of quantum mechanics.",
            students: 120,
            price: 59.99,
            discount: false,
            rating: 4,
            type: "live",
        },
        {
            id: 3,
            title: "Organic Chemistry",
            category: "Chemistry",
            teacher: "Dr. Alice Brown",
            pictureUrl: "/exmp1.jpg",
            description: "Master organic chemistry with hands-on problem-solving.",
            students: 180,
            price: 69.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
        {
            id: 4,
            title: "Human Anatomy",
            category: "Biology",
            teacher: "Dr. Emily White",
            pictureUrl: "/exmp1.jpg",
            description: "A deep dive into the structure and function of the human body.",
            students: 250,
            price: 79.99,
            discount: false,
            rating: 4,
            type: "live",
        },
        {
            id: 5,
            title: "Introduction to Scientific Research",
            category: "Science",
            teacher: "Dr. Mark Wilson",
            pictureUrl: "/exmp1.jpg",
            description: "Learn the fundamentals of scientific research methods.",
            students: 95,
            price: 39.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
        {
            id: 6,
            title: "French for Beginners",
            category: "French",
            teacher: "Prof. Sophie Dupont",
            pictureUrl: "/exmp1.jpg",
            description: "Start your journey in learning French from scratch.",
            students: 300,
            price: 29.99,
            discount: false,
            rating: 4,
            type: "live",
        },
        {
            id: 7,
            title: "Advanced English Writing",
            category: "English",
            teacher: "Mr. James Anderson",
            pictureUrl: "/exmp1.jpg",
            description: "Improve your writing skills for academic and professional success.",
            students: 170,
            price: 34.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
        {
            id: 8,
            title: "World History Overview",
            category: "History",
            teacher: "Dr. Robert Martin",
            pictureUrl: "/exmp1.jpg",
            description: "A comprehensive study of major historical events and civilizations.",
            students: 140,
            price: 45.99,
            discount: false,
            rating: 4,
            type: "live",
        },
        {
            id: 9,
            title: "Geography and Natural Disasters",
            category: "Geography",
            teacher: "Prof. Laura Green",
            pictureUrl: "/exmp1.jpg",
            description: "Understand how geography shapes the world and impacts natural disasters.",
            students: 110,
            price: 42.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
        {
            id: 10,
            title: "Philosophy of Ethics",
            category: "Philosophy",
            teacher: "Dr. Paul Thompson",
            pictureUrl: "/exmp1.jpg",
            description: "Explore the fundamental questions of morality and human ethics.",
            students: 80,
            price: 37.99,
            discount: false,
            rating: 4,
            type: "live",
        },
        {
            id: 11,
            title: "Principles of Economics",
            category: "Economics",
            teacher: "Prof. Sarah Miller",
            pictureUrl: "/exmp1.jpg",
            description: "Learn the basics of economic theory and market dynamics.",
            students: 200,
            price: 55.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
        {
            id: 12,
            title: "Introduction to Programming",
            category: "Computer Science",
            teacher: "Mr. Daniel Johnson",
            pictureUrl: "/exmp1.jpg",
            description: "Start your coding journey with Python and JavaScript.",
            students: 500,
            price: 69.99,
            discount: false,
            rating: 4,
            type: "live",
        },
        {
            id: 13,
            title: "Mechanical Engineering Fundamentals",
            category: "Génie Mécanique",
            teacher: "Dr. Michael Brown",
            pictureUrl: "/exmp1.jpg",
            description: "Learn the basics of mechanical systems and engineering principles.",
            students: 130,
            price: 64.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
        {
            id: 14,
            title: "Civil Engineering and Construction",
            category: "Génie Civil",
            teacher: "Prof. Anna Williams",
            pictureUrl: "/exmp1.jpg",
            description: "Understand the fundamentals of civil engineering and architecture.",
            students: 90,
            price: 58.99,
            discount: false,
            rating: 4,
            type: "live",
        },
        {
            id: 15,
            title: "Electrical Circuits and Systems",
            category: "Génie Électrique",
            teacher: "Dr. Chris Evans",
            pictureUrl: "/exmp1.jpg",
            description: "Dive into the world of electrical circuits and power systems.",
            students: 160,
            price: 47.99,
            discount: true,
            rating: 4,
            type: "prerecorded",
        },
    ];




export default { categories, courses };
