import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/context";

export const metadata: Metadata = {
  title: "E-learning Platform",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <AppProvider>
          <main>{children}</main>

          <footer></footer>
        </AppProvider>
      </body>
    </html>
  );
}
